services:
  postgres:
    image: postgres:18
    ports:
      - "5433:5432"
    env_file:
      - ./backend/.env
    restart: unless-stopped
  redis:
    image: redis:latest
    restart: unless-stopped
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=postgres
      - REDIS_URL=redis://redis:6379
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
  cron:
    build: ./backend
    command: node cron/cron.js
    restart: unless-stopped
  frontend:
    build: ./frontend/product-tracker
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped